# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-app-chart.fullname" . }}
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
